#!/bin/bash

function _disable_service () {
  local _name=$1
  systemctl stop _name
  systemctl disable _name
  systemctl disable _name
}

dockercompose=${1##*@}

if ! test -L /etc/docker-compose/${dockercompose%.*}; then
  echo "Docker-Compose ${dockercompose%.*} n'existe pas et ne peut être desactive"
  exit 1
fi

_disable_service pull-docker-compose@${dockercompose%.*}.service
_disable_service pull-docker-compose@${dockercompose%.*}.timer
_disable_service docker-compose@${dockercompose%.*}.service
systemctl daemon-reload

cd /etc/docker-compose && \
 rm ${dockercompose%.*}
